BaseUrl= "http://www.chrispiraino.com/"
LanguageCode= "en-US"
Title= "The Event Horizon"
paginate = 5
#DisqusShortname = ""
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Chris Piraino's random musings"
  cover = "images/cover.jpg"
  author = "Chris Piraino"
  authorlocation = "San Francisco, CA"
  authorwebsite = "http://www.chrispiraino.com/"
#  bio= ""
#  logo = ""
#  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = ""
  githubName = "crhino"
  #twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
